before_install:
 - cd BayesianTools
 

language: r
r:
  - oldrel
  - release
  - devel
  
cache: packages

# Install nlopt package to help nloptr install
# glpk-utils and libglpk-dev are needed because of DHARMa #166
addons:
  apt:
    packages:
      - libnlopt-dev
      - glpk-utils
      - libglpk-dev
